#!/bin/bash

# Get the Python file name from the environment variable
pyfile=$PYFILE

# Compile the Python script using the "-m py_compile" option
python -m py_compile $pyfile

# Get the base name of the Python file without the extension
basename=$(basename $pyfile)
filename="${basename%.*}"

# Rename the compiled file to have the ".pyc" extension
mv "${filename}.pyc" "${filename}c"
